/**
 * Acme Cafe App
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


@ApiModel(description = "")
public class BlacklistParam  {
  
  @SerializedName("costumerUuid")
  private String costumerUuid = null;
  @SerializedName("myUser")
  private String myUser = null;
  @SerializedName("myPass")
  private String myPass = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCostumerUuid() {
    return costumerUuid;
  }
  public void setCostumerUuid(String costumerUuid) {
    this.costumerUuid = costumerUuid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMyUser() {
    return myUser;
  }
  public void setMyUser(String myUser) {
    this.myUser = myUser;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMyPass() {
    return myPass;
  }
  public void setMyPass(String myPass) {
    this.myPass = myPass;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlacklistParam blacklistParam = (BlacklistParam) o;
    return (costumerUuid == null ? blacklistParam.costumerUuid == null : costumerUuid.equals(blacklistParam.costumerUuid)) &&
        (myUser == null ? blacklistParam.myUser == null : myUser.equals(blacklistParam.myUser)) &&
        (myPass == null ? blacklistParam.myPass == null : myPass.equals(blacklistParam.myPass));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (costumerUuid == null ? 0: costumerUuid.hashCode());
    result = 31 * result + (myUser == null ? 0: myUser.hashCode());
    result = 31 * result + (myPass == null ? 0: myPass.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlacklistParam {\n");
    
    sb.append("  costumerUuid: ").append(costumerUuid).append("\n");
    sb.append("  myUser: ").append(myUser).append("\n");
    sb.append("  myPass: ").append(myPass).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
