/**
 * Acme Cafe App
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


@ApiModel(description = "")
public class Blacklist {

  @SerializedName("costumerUuid")
  private String costumerUuid = null;
  @SerializedName("id")
  private Integer id = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCostumerUuid() {
    return costumerUuid;
  }

  public void setCostumerUuid(String costumerUuid) {
    this.costumerUuid = costumerUuid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Blacklist blacklist = (Blacklist) o;
    return (costumerUuid == null ? blacklist.costumerUuid == null : costumerUuid.equals(blacklist.costumerUuid)) &&
            (id == null ? blacklist.id == null : id.equals(blacklist.id));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (costumerUuid == null ? 0 : costumerUuid.hashCode());
    result = 31 * result + (id == null ? 0 : id.hashCode());
    return result;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Blacklist {\n");

    sb.append("  costumerUuid: ").append(costumerUuid).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
