/**
 * Acme Cafe App
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.Requestline;
import io.swagger.client.model.Voucher;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class LinesVouchersResponse  {
  
  @SerializedName("requestlines")
  private List<Requestline> requestlines = null;
  @SerializedName("vouchers")
  private List<Voucher> vouchers = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<Requestline> getRequestlines() {
    return requestlines;
  }
  public void setRequestlines(List<Requestline> requestlines) {
    this.requestlines = requestlines;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<Voucher> getVouchers() {
    return vouchers;
  }
  public void setVouchers(List<Voucher> vouchers) {
    this.vouchers = vouchers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinesVouchersResponse linesVouchersResponse = (LinesVouchersResponse) o;
    return (requestlines == null ? linesVouchersResponse.requestlines == null : requestlines.equals(linesVouchersResponse.requestlines)) &&
        (vouchers == null ? linesVouchersResponse.vouchers == null : vouchers.equals(linesVouchersResponse.vouchers));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (requestlines == null ? 0: requestlines.hashCode());
    result = 31 * result + (vouchers == null ? 0: vouchers.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinesVouchersResponse {\n");
    
    sb.append("  requestlines: ").append(requestlines).append("\n");
    sb.append("  vouchers: ").append(vouchers).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
