/**
 * Acme Cafe App
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class ProductParam  {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("active")
  private Boolean active = null;
  @SerializedName("unitprice")
  private Float unitprice = null;
  @SerializedName("myUser")
  private String myUser = null;
  @SerializedName("myPass")
  private String myPass = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getActive() {
    return active;
  }
  public void setActive(Boolean active) {
    this.active = active;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Float getUnitprice() {
    return unitprice;
  }
  public void setUnitprice(Float unitprice) {
    this.unitprice = unitprice;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMyUser() {
    return myUser;
  }
  public void setMyUser(String myUser) {
    this.myUser = myUser;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMyPass() {
    return myPass;
  }
  public void setMyPass(String myPass) {
    this.myPass = myPass;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductParam productParam = (ProductParam) o;
    return (name == null ? productParam.name == null : name.equals(productParam.name)) &&
        (active == null ? productParam.active == null : active.equals(productParam.active)) &&
        (unitprice == null ? productParam.unitprice == null : unitprice.equals(productParam.unitprice)) &&
        (myUser == null ? productParam.myUser == null : myUser.equals(productParam.myUser)) &&
        (myPass == null ? productParam.myPass == null : myPass.equals(productParam.myPass));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (name == null ? 0: name.hashCode());
    result = 31 * result + (active == null ? 0: active.hashCode());
    result = 31 * result + (unitprice == null ? 0: unitprice.hashCode());
    result = 31 * result + (myUser == null ? 0: myUser.hashCode());
    result = 31 * result + (myPass == null ? 0: myPass.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductParam {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  active: ").append(active).append("\n");
    sb.append("  unitprice: ").append(unitprice).append("\n");
    sb.append("  myUser: ").append(myUser).append("\n");
    sb.append("  myPass: ").append(myPass).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
