/**
 * Acme Cafe App
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


@ApiModel(description = "")
public class Request {

  @SerializedName("costumerUuid")
  private String costumerUuid = null;
  @SerializedName("pin")
  private String pin = null;
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("number")
  private Integer number = null;
  @SerializedName("vouchers")
  private List<Voucher> vouchers = null;
  @SerializedName("requestlines")
  private List<Requestline> requestlines = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCostumerUuid() {
    return costumerUuid;
  }

  public void setCostumerUuid(String costumerUuid) {
    this.costumerUuid = costumerUuid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPin() {
    return pin;
  }

  public void setPin(String pin) {
    this.pin = pin;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getNumber() {
    return number;
  }

  public void setNumber(Integer number) {
    this.number = number;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Voucher> getVouchers() {
    return vouchers;
  }

  public void setVouchers(List<Voucher> vouchers) {
    this.vouchers = vouchers;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Requestline> getRequestlines() {
    return requestlines;
  }

  public void setRequestlines(List<Requestline> requestlines) {
    this.requestlines = requestlines;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Request request = (Request) o;
    return (costumerUuid == null ? request.costumerUuid == null : costumerUuid.equals(request.costumerUuid)) &&
            (pin == null ? request.pin == null : pin.equals(request.pin)) &&
            (id == null ? request.id == null : id.equals(request.id)) &&
            (number == null ? request.number == null : number.equals(request.number)) &&
            (vouchers == null ? request.vouchers == null : vouchers.equals(request.vouchers)) &&
            (requestlines == null ? request.requestlines == null : requestlines.equals(request.requestlines));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (costumerUuid == null ? 0 : costumerUuid.hashCode());
    result = 31 * result + (pin == null ? 0 : pin.hashCode());
    result = 31 * result + (id == null ? 0 : id.hashCode());
    result = 31 * result + (number == null ? 0 : number.hashCode());
    result = 31 * result + (vouchers == null ? 0 : vouchers.hashCode());
    result = 31 * result + (requestlines == null ? 0 : requestlines.hashCode());
    return result;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Request {\n");

    sb.append("  costumerUuid: ").append(costumerUuid).append("\n");
    sb.append("  pin: ").append(pin).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  number: ").append(number).append("\n");
    sb.append("  vouchers: ").append(vouchers).append("\n");
    sb.append("  requestlines: ").append(requestlines).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
