/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 16-Oct-2016 02:57:07 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS Costumer CASCADE
;

DROP TABLE IF EXISTS Menu CASCADE
;

DROP TABLE IF EXISTS MenuProduct CASCADE
;

DROP TABLE IF EXISTS Product CASCADE
;

DROP TABLE IF EXISTS Request CASCADE
;

DROP TABLE IF EXISTS RequestLine CASCADE
;

DROP TABLE IF EXISTS RequestRequestLine CASCADE
;

DROP TABLE IF EXISTS RequestVoucher CASCADE
;

DROP TABLE IF EXISTS Voucher CASCADE
;

/* Create Tables */

CREATE TABLE Costumer
(
	CostumerId integer NOT NULL,
	Name text NOT NULL,
	Pin text NOT NULL,
	CreditCard text NOT NULL,
	Username text NOT NULL,
	Password text NOT NULL,
	CreditCardExpiration timestamp
)
;

CREATE TABLE Menu
(
	MenuId integer NOT NULL,
	Name text,
	Active boolean NOT NULL
)
;

CREATE TABLE MenuProduct
(
	MenuId integer NOT NULL,
	ProductId integer NOT NULL
)
;

CREATE TABLE Product
(
	ProductId integer NOT NULL,
	Name text NOT NULL
)
;

CREATE TABLE Request
(
	RequestId integer NOT NULL,
	CostumerId integer NOT NULL
)
;

CREATE TABLE RequestLine
(
	RequestLineId integer NOT NULL,
	ProductId integer NOT NULL,
	Quantity integer NOT NULL,
	UnitPrice real NOT NULL
)
;

CREATE TABLE RequestRequestLine
(
	RequestId integer NOT NULL,
	RequestLineId integer NOT NULL
)
;

CREATE TABLE RequestVoucher
(
	VoucherId integer NOT NULL,
	RequestId integer NOT NULL
)
;

CREATE TABLE Voucher
(
	VoucherId integer NOT NULL,
	Key text NOT NULL,
	Number integer NOT NULL,
	Type bytea NOT NULL,
	CostumerId integer NOT NULL,
	IsUsed boolean NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Costumer ADD CONSTRAINT PK_Costumer
	PRIMARY KEY (CostumerId)
;

ALTER TABLE Costumer ADD CONSTRAINT UQ_Costumer_Username UNIQUE (Username)
;

ALTER TABLE Menu ADD CONSTRAINT PK_Menu
	PRIMARY KEY (MenuId)
;

ALTER TABLE MenuProduct ADD CONSTRAINT PK_MenuProduct
	PRIMARY KEY (MenuId,ProductId)
;

ALTER TABLE Product ADD CONSTRAINT PK_Product
	PRIMARY KEY (ProductId)
;

ALTER TABLE Product ADD CONSTRAINT UQ_Product_Name UNIQUE (Name)
;

ALTER TABLE Request ADD CONSTRAINT PK_Order
	PRIMARY KEY (RequestId)
;

ALTER TABLE RequestLine ADD CONSTRAINT PK_RequestLine
	PRIMARY KEY (RequestLineId)
;

ALTER TABLE RequestRequestLine ADD CONSTRAINT PK_OrderRequestLine
	PRIMARY KEY (RequestId,RequestLineId)
;

CREATE INDEX IXFK_OrderRequestLine_Order ON RequestRequestLine (RequestId ASC)
;

ALTER TABLE RequestVoucher ADD CONSTRAINT PK_OrderVoucher
	PRIMARY KEY (VoucherId,RequestId)
;

CREATE INDEX IXFK_OrderVoucher_Order ON RequestVoucher (RequestId ASC)
;

ALTER TABLE Voucher ADD CONSTRAINT PK_Voucher
	PRIMARY KEY (VoucherId)
;

ALTER TABLE Voucher ADD CONSTRAINT UQ_Voucher_Key UNIQUE (Key)
;

ALTER TABLE Voucher ADD CONSTRAINT UQ_Voucher_Number UNIQUE (Number)
;

/* Create Foreign Key Constraints */

ALTER TABLE MenuProduct ADD CONSTRAINT FK_MenuProduct_Menu
	FOREIGN KEY (MenuId) REFERENCES Menu (MenuId) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE MenuProduct ADD CONSTRAINT FK_MenuProduct_Product
	FOREIGN KEY (ProductId) REFERENCES Product (ProductId) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE Request ADD CONSTRAINT FK_Order_Costumer
	FOREIGN KEY (CostumerId) REFERENCES Costumer (CostumerId) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE RequestLine ADD CONSTRAINT FK_RequestLine_Product
	FOREIGN KEY (ProductId) REFERENCES Product (ProductId) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE RequestRequestLine ADD CONSTRAINT FK_OrderRequestLine_Order
	FOREIGN KEY (RequestId) REFERENCES Request (RequestId) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE RequestRequestLine ADD CONSTRAINT FK_OrderRequestLine_RequestLine
	FOREIGN KEY (RequestLineId) REFERENCES RequestLine (RequestLineId) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE RequestVoucher ADD CONSTRAINT FK_OrderVoucher_Order
	FOREIGN KEY (RequestId) REFERENCES Request (RequestId) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE RequestVoucher ADD CONSTRAINT FK_OrderVoucher_Voucher
	FOREIGN KEY (VoucherId) REFERENCES Voucher (VoucherId) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE Voucher ADD CONSTRAINT FK_Voucher_Costumer
	FOREIGN KEY (CostumerId) REFERENCES Costumer (CostumerId) ON DELETE Cascade ON UPDATE No Action
;
