/**
 * Acme Cafe App
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class Voucher  {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("type")
  private Integer type = null;
  @SerializedName("key")
  private String key = null;
  @SerializedName("costumerUuid")
  private String costumerUuid = null;
  @SerializedName("requestId")
  private Integer requestId = null;
  @SerializedName("isused")
  private Boolean isused = null;
  @SerializedName("number")
  private Integer number = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getType() {
    return type;
  }
  public void setType(Integer type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getKey() {
    return key;
  }
  public void setKey(String key) {
    this.key = key;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCostumerUuid() {
    return costumerUuid;
  }
  public void setCostumerUuid(String costumerUuid) {
    this.costumerUuid = costumerUuid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getRequestId() {
    return requestId;
  }
  public void setRequestId(Integer requestId) {
    this.requestId = requestId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getIsused() {
    return isused;
  }
  public void setIsused(Boolean isused) {
    this.isused = isused;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getNumber() {
    return number;
  }
  public void setNumber(Integer number) {
    this.number = number;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Voucher voucher = (Voucher) o;
    return (id == null ? voucher.id == null : id.equals(voucher.id)) &&
        (type == null ? voucher.type == null : type.equals(voucher.type)) &&
        (key == null ? voucher.key == null : key.equals(voucher.key)) &&
        (costumerUuid == null ? voucher.costumerUuid == null : costumerUuid.equals(voucher.costumerUuid)) &&
        (requestId == null ? voucher.requestId == null : requestId.equals(voucher.requestId)) &&
        (isused == null ? voucher.isused == null : isused.equals(voucher.isused)) &&
        (number == null ? voucher.number == null : number.equals(voucher.number));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (type == null ? 0: type.hashCode());
    result = 31 * result + (key == null ? 0: key.hashCode());
    result = 31 * result + (costumerUuid == null ? 0: costumerUuid.hashCode());
    result = 31 * result + (requestId == null ? 0: requestId.hashCode());
    result = 31 * result + (isused == null ? 0: isused.hashCode());
    result = 31 * result + (number == null ? 0: number.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Voucher {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  key: ").append(key).append("\n");
    sb.append("  costumerUuid: ").append(costumerUuid).append("\n");
    sb.append("  requestId: ").append(requestId).append("\n");
    sb.append("  isused: ").append(isused).append("\n");
    sb.append("  number: ").append(number).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
